export { useBikeStore, availableLocations, bikeModels, bikeColors } from './bike'
export { useUserStore } from './user'
export { useReservationStore } from './reservation'
export { useAuthStore } from './auth'
export { useModalStore } from './modals'

export type { Bike } from './bike'
export type { User, RegisterCredentials, UpdateCredentials } from './user'
export type { Reservation } from './reservation'
export type { LoginCredentials } from './auth'